name: asadah
description: Sebuah Gadai Syariah.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.3
  google_fonts: ^6.1.0
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/images/launcher.png"
  android12:
    image: assets/images/android12splash.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
